### PR TITLE
Add a Github Actions workflow to test building snebu for PRs & commits

### PR DESCRIPTION
**Pull request by herbygillot**
This should be ready to merge, as it is now successfully building `snebu` via Github actions: https://github.com/herbygillot/snebu/actions?query=branch%3Aci-gh-actions

### CODE REVIEW

**Comment by derekp7** [comment]
What does this commit do -- is it for a CI/CD workflow or similar?  I'll have to read up on Github Actions -- I'm still "old school Unix" (used to programming on a serial-line connected 3151 terminal), so I need to study up on the current available tooling.  Thanks.

**Comment by herbygillot** [comment]
> What does this commit do -- is it for a CI/CD workflow or similar? I'll have to read up on Github Actions -- I'm still "old school Unix" (used to programming on a serial-line connected 3151 terminal), so I need to study up on the current available tooling. Thanks.

Yes, this provides CI via Github Actions. Actions are defined via "workflows", in YAML files within a `.github/workflows` directory in the source tree.

The workflow as currently defined in this YAML file does the following:

1. Creates an Ubuntu 20.04 environment
2. Checks out the current source tree (the current branch or current commit in question)
3. Installs `snebu`'s dependencies (liblzo, Sqlite3 & libssl)
4. Build `snebu` (`make`)
5. Install `snebu` (`make install`)

This workflow is configured to perform these actions on every commit or pull request submitted (`on: push (commits), pull-requests`)

In this way, a test build can be performed for every pull request opened against `snebu`.

I'm no Github Actions expert myself so it may still need some tweaks.

**Comment by derekp7** [comment]
Ah, makes sense.  Looks like this can eventually be used to run an end-to-end validation suite which will be good.  I'm working on a full test script on the side, there are a number of edge-cases I need to put in, but will start off with the basic backup/restore/verify/expire/purge tests.

**Comment by herbygillot** [comment]
> So does this kick off only on pull requests, or does it also activate when I do a git push from my end? (I'll read through the docs, now that I got a feel for what it is).

Yes, as mentioned above, Github Actions will fire on every push of commits, and pull requests.

This is set by the `on` section in the workflow YAML:
https://github.com/derekp7/snebu/blob/af1bd073d314dc04425722476b352698caa9fddf/.github/workflows/main.yml#L6-L8

You can now see the pass/fail marks on the commit in the commits view, as well as the Actions tab of the `snebu` repo: https://github.com/derekp7/snebu/actions

**Comment by derekp7** [comment]
Thanks a bunch!  This is the type of assistance I need on this project, especially since I'm working on getting it packaged up for various distributions.  The next thing I should work on is setting up a discussion list.  I had one previously using Google Groups, but the only activity on it was weird spam.  I see that GitHub now has a discussion forum feature, I may look into that.  Also I've committed additional changes to the Makefile that was suggested on the Fedora dev mailing list (to honor CFLAGS and LDFLAGS that one of the rpm build macros pushes).

**Comment by herbygillot** [comment]
I'm glad you find it useful.

> ...I'm working on getting it packaged up for various distributions. 

Github Actions supports Docker, which can be used to test in different OS combinations.  You could probably incorporate building the RPM in a CentOS container.  As it is right now, the actions in the workflow are being run directly in the Github Action Ubuntu environment.

> The next thing I should work on is setting up a discussion list.

I don't have a lot of input there; I don't know that I've seen any projects that use the Github Discussions feature, but perhaps that will become more popular over time 🤷🏾‍♂️

> (to honor CFLAGS and LDFLAGS that one of the rpm build macros pushes).

The `CFLAGS` and `LDFLAGS` are definitely needed.  One comment I would have looking at the `Makefile` though is that only `CFLAGS` should be present in the `%.o: %.c` target, but both `CFLAGS` and `LDFLAGS` should be present in the `snebu` and `tarcrypt` targets (in which currently neither are present).

This is because `LDFLAGS` should be present where linking is happening (which is happening when building `snebu` and `tarcrypt` binaries).  `CFLAGS` should be present whenever the compiler is being invoked (`$(CC)`).  Just my 2 cents.

**Pull request merged**
